language: csharp
dotnet: 6.0.101
mono: none
os:
  - linux
  - osx

before_install:
  - nvm install 16.13.2
  - nvm use 16.13.2

script:
  - dotnet tool restore
  - dotnet paket restore
  - dotnet run --project tests/tests.fsproj